# Generated by Django 4.0.4 on 2022-05-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ok_corporate', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok_corporate.company')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ok_corporate.review')),
            ],
        ),
    ]
